const BASE_TAB_HEIGHT = 40;
const MAX_COLLAPSED_TAB_WIDTH = 300;
const MAX_EXPANDED_TAB_WIDTH = 380;
const TAB_PADDING = 16;
const TAB_PADDINGS = TAB_PADDING * 2;
const DEFAULT_LINES_AMOUNT = 1;
const LINE_HEIGHT = 28;
const MAXIMUM_LINES = 3;
const TAB_MARGIN = 12;

export {
  BASE_TAB_HEIGHT,
  MAX_COLLAPSED_TAB_WIDTH,
  MAX_EXPANDED_TAB_WIDTH,
  TAB_PADDING,
  TAB_PADDINGS,
  DEFAULT_LINES_AMOUNT,
  LINE_HEIGHT,
  MAXIMUM_LINES,
  TAB_MARGIN,
};
